/* global window */
/* ─────────────────────────────────────────────────────────
   Shared data — loaded as a plain <script> on every page.
   window.PROJECTS  window.PRACTICES  window.UPCOMING  window.LEARNING  window.CREATIVE
   slug = URL-safe id used as ?id=… in detail URLs.
   ───────────────────────────────────────────────────────── */

window.PROJECTS = [
  {
    id: 5, slug: 'explore-your-campus',
    cat: 'UI/UX · Web',
    title: 'Explore Your <em>Campus</em>',
    teaser: 'An interactive web guide for new ANU students — built during my role as Web Project Officer.',
    tone: 'cherry', label: 'WEB', meta: 'UI/UX · Web · 2024',
    category: 'ux', featured: true, glyph: 'pin', stickers: 'campus',
    year: 2024, role: 'Web Project Officer, ANU',
    client: 'Australian National University', duration: '3 months',
    lede: 'New students don\'t need a map. They need to know where to go on a bad day.',
    sections: [
      { kind: 'block', tag: 'Brief', title: 'The campus map problem.', body: 'ANU is a large campus that can feel overwhelming — especially for international students arriving in a new country. The existing wayfinding was a static PDF and a Buildings & Grounds page nobody opened. We were asked to build something better. The brief was loose, which turned out to be a gift.' },
      { kind: 'block', tag: 'Insight', title: 'They don\'t want a tour. They want to feel ready.', body: 'Early user interviews revealed that new students don\'t primarily need navigation — they need orientation. They need to know where to go when they\'re overwhelmed, lost, or hungry at 6pm. We restructured the experience around moments ("First week", "Late night", "When you\'re stuck") rather than categories ("Admin", "Academic", "Recreation").' },
      { kind: 'metrics', items: [
        { num: '4k+', label: 'Sessions in first semester' },
        { num: '3', label: 'User interview rounds' },
        { num: '78%', label: 'Students who found it genuinely useful' },
        { num: '1', label: 'PDF map replaced' },
      ] },
      { kind: 'block', tag: 'Outcome', title: 'Moment-based navigation.', body: 'The final experience is structured around eight "moments" rather than a category taxonomy. Each moment surfaces the three most relevant places on campus, with short context — not an address, but "the cafe open when the library closes." Student feedback collected at Orientation and mid-semester showed significant improvement over the baseline year.' },
    ],
  },
  {
    id: 1, slug: 'ion-studio',
    cat: 'Start-up · AI Integration',
    title: 'Ion <em>Studio</em>',
    teaser: 'A mobile AI studio helping app teams ship intelligent features — without rebuilding from scratch.',
    tone: 'cherry', label: 'FEATURED', meta: 'Founder · 2024–present',
    category: 'startup', glyph: 'flame', stickers: 'ion',
    year: 2024, role: 'Co-founder',
    client: 'Self-initiated → B2B clients', duration: 'Ongoing',
    lede: 'Ion Studio bridges the gap between mobile apps and AI — helping teams integrate intelligent features without rebuilding their entire product.',
    sections: [
      { kind: 'block', tag: 'Origin', title: 'The gap nobody was filling.', body: 'Most app teams know AI could transform their product. What they lack is a clear path from "we should add AI" to a shipped feature that actually helps users. Agency work is too slow; hiring AI specialists is too expensive; and most consultants hand over a deck, not working code. Ion Studio was built for that gap — rapid AI integration that fits inside an existing team\'s sprint.' },
      { kind: 'block', tag: 'Approach', title: 'Audit, prototype, hand off.', body: 'We run a structured three-phase process: first, a focused audit of the existing app to identify the 3–5 moments where AI creates genuine value, not just novelty; second, a working prototype the client team can test with real users; third, integration-ready specs and support through the first AI feature ship. The process is designed to leave teams capable of extending AI themselves — not dependent on us.' },
      { kind: 'metrics', items: [
        { num: '2', label: 'Products shipping under Ion Studio' },
        { num: '3', label: 'Avg weeks from audit to prototype' },
        { num: '100%', label: 'Client retention to date' },
        { num: '2', label: 'Co-founders building this' },
      ] },
      { kind: 'pull', text: 'The best AI integration is the one users don\'t notice — they just think the app got smarter.' },
    ],
  },
  {
    id: 2, slug: 'wheeltodo',
    cat: 'UI/UX · Mobile App',
    title: 'Wheel<em>ToDo</em>',
    teaser: 'A task and route-planning app designed for wheelchair users — accessibility as the starting point, not an afterthought.',
    tone: 'lilac', label: 'APP', meta: 'UI/UX · 2025',
    category: 'ux', glyph: 'heart', stickers: 'wheel',
    year: 2025, role: 'Lead designer & developer',
    client: 'Ion Studio', duration: '4 months',
    lede: 'Most task apps treat accessibility as a setting. WheelToDo starts there.',
    sections: [
      { kind: 'block', tag: 'Problem', title: 'Accessibility bolted on is accessibility broken.', body: 'Existing to-do and route apps offer accessibility as add-ons — larger text, voice control — but the core experience wasn\'t built for users navigating the world in a wheelchair. WheelToDo starts from a different premise: what if the primary user manages tasks one-handed, needs route elevation data, and wants to know if a "10-minute walk" is actually accessible for them?' },
      { kind: 'block', tag: 'Approach', title: 'Design with, not for.', body: 'We ran six co-design sessions with wheelchair users in Canberra and online. Every interaction model was tested with one-handed use as the default. The route planner integrates elevation and surface-quality data so users can trust what "accessible route" means. We removed features that didn\'t survive contact with real users — including a gesture system that only worked well for people with full hand mobility.' },
      { kind: 'metrics', items: [
        { num: '6', label: 'Co-design sessions' },
        { num: '1-hand', label: 'Default interaction model' },
        { num: '92%', label: 'Task completion rate (usability testing)' },
        { num: '3.8s', label: 'Avg time to add a task' },
      ] },
      { kind: 'block', tag: 'Outcome', title: 'A small app with outsized usefulness.', body: 'WheelToDo launched in beta with users from the co-design sessions. The most-used feature isn\'t the route planner — it\'s shared task lists, which users adapted for grocery runs, hospital appointments, and everything in between. The app is growing by word of mouth within the disability community, which is the only growth signal we care about.' },
    ],
  },
  {
    id: 3, slug: 'cribd',
    cat: 'UI/UX · Start-up',
    title: 'Cribd<em>.</em>',
    teaser: 'A student accommodation platform connecting renters with verified short-stay housing — from uni project to real product.',
    tone: 'bubble', label: 'UX', meta: 'UI/UX · Product · 2023–2024',
    category: 'ux', glyph: 'home', stickers: 'cribd',
    year: 2023, role: 'Lead designer & co-founder',
    client: 'University project → Ion Studio', duration: '12 months',
    lede: 'Cribd. started as a university brief and became something a small team actually wanted to build.',
    sections: [
      { kind: 'block', tag: 'Origin', title: 'A real problem, lived personally.', body: 'Finding student accommodation in Canberra is genuinely difficult — the market is thin, verification is inconsistent, and short-stay options for semester exchanges barely exist. Cribd. was born from that frustration. What started as a university assignment became a product worth continuing: a two-sided marketplace that puts trust at the centre.' },
      { kind: 'block', tag: 'Design', title: 'Trust is the product.', body: 'The hardest design problem in a student accommodation marketplace isn\'t the search UX — it\'s trust. We designed a lightweight verification flow that feels like onboarding rather than a security checkpoint, and a listing format that surfaces what students actually need (campus proximity, lease flexibility, who else is in the property) before showing price.' },
      { kind: 'metrics', items: [
        { num: '120+', label: 'Beta users in first semester' },
        { num: '4.4★', label: 'Average listing trust score' },
        { num: '2', label: 'Research rounds before first pixel' },
        { num: '1', label: 'University award for the concept' },
      ] },
      { kind: 'pull', text: 'The trust flow isn\'t a gate. It\'s the product. Design it like it matters.' },
    ],
  },
  {
    id: 4, slug: 'leftover-app',
    cat: 'UI/UX · Social Impact',
    title: 'The Leftover <em>App</em>',
    teaser: 'A food surplus platform connecting cafes with nearby people — a university capstone built for real communities.',
    tone: 'moss', label: 'UNI', meta: 'UI/UX · 2023',
    category: 'ux', glyph: 'flower', stickers: 'leftover',
    year: 2023, role: 'Lead designer & researcher',
    client: 'ANU capstone project', duration: '6 months',
    lede: 'A food surplus app that actually got used — because the people who needed it helped design it.',
    sections: [
      { kind: 'block', tag: 'Problem', title: 'Food waste is a design problem.', body: 'Every day, cafes and households in Canberra discard food that nearby people would eat. The barrier isn\'t willingness — it\'s coordination. Existing solutions require too much planning, don\'t fit into the end-of-day rush at a cafe, and put the burden on the people with the least time: the staff closing up at 5pm.' },
      { kind: 'block', tag: 'Approach', title: 'The listing takes 60 seconds.', body: 'We tested six listing flows with cafe staff at the end of real services. Everything over 60 seconds was abandoned. The final flow has three fields, a pre-filled time window, and a share button. On the receiver side, we built around "on my way home" — proximity-first, no planning required. Both sides were designed to work with the grain of existing behaviour, not against it.' },
      { kind: 'metrics', items: [
        { num: '3', label: 'Fields in the final listing flow' },
        { num: '60s', label: 'Maximum listing time (design target)' },
        { num: '8', label: 'Cafe partners in pilot' },
        { num: '340', label: 'Meals matched in pilot semester' },
      ] },
    ],
  },
  {
    id: 6, slug: 'ab-testing-calculator',
    cat: 'Data & Analytics',
    title: 'A/B Testing <em>Calculator</em>',
    teaser: 'A clean statistical significance tool built because every existing one required a stats degree to interpret.',
    tone: 'ink', label: 'TOOL', meta: 'Data · Personal · 2025',
    category: 'data', glyph: 'star', stickers: 'abtest',
    year: 2025, role: 'Designer & developer',
    client: 'Self-initiated', duration: '3 weeks',
    lede: 'Every A/B testing tool I found either gave me a number or gave me a lecture. I wanted something in between.',
    sections: [
      { kind: 'block', tag: 'Problem', title: 'Statistical significance is a communication problem.', body: 'Most A/B testing calculators either output a raw p-value (which non-statisticians misread) or hide the maths and return a green/red result (which creates false confidence). The gap between "technically significant" and "worth acting on" is where most bad decisions happen — and no tool was bridging it honestly.' },
      { kind: 'block', tag: 'Approach', title: 'Show the interpretation, not just the number.', body: 'The calculator outputs three layers: the statistical result, a plain-language interpretation calibrated to sample size and effect magnitude, and a "minimum detectable effect" panel showing what the test actually had the power to detect. The goal was to make results honest and actionable, not just fast.' },
      { kind: 'metrics', items: [
        { num: '<2s', label: 'Time to result' },
        { num: '3', label: 'Output layers (result · interpretation · context)' },
        { num: '100%', label: 'Client-side — no data sent anywhere' },
        { num: '1', label: 'Reason to build it: I needed it' },
      ] },
    ],
  },
];

window.PRACTICES = [
  {
    slug: 'ux-product-design',
    tone: 'cherry', tag: 'FOCUS 01',
    title: 'UX & Product Design',
    short: 'Research, prototyping, and interface design for mobile and web — from first interview to final handoff.',
    tools: 'Figma · React Native · Notion',
    lede: 'Most of the work is not the artefact. It\'s sitting in the room before there is one.',
    body: 'I lead user research, information architecture, interaction design, and design-system work — usually for mobile-first products and web experiences. I take work from discovery through to engineering handoff, and I stay around for the messy bit after launch when things actually start to behave like a product.',
    methods: [
      { name: 'User research', detail: 'In-context observation, co-design sessions, jobs-to-be-done interviews.' },
      { name: 'Information architecture', detail: 'Card-sorting, tree-testing, taxonomy work for content-heavy products.' },
      { name: 'Interaction prototyping', detail: 'High-fidelity prototypes that survive contact with engineering.' },
      { name: 'Accessibility-first design', detail: 'Designing for the hardest use cases first — everything else gets easier.' },
    ],
    relatedProjectIds: [2, 4],
  },
  {
    slug: 'ai-integration',
    tone: 'bubblegum', tag: 'FOCUS 02',
    title: 'AI Integration',
    short: 'Helping mobile and web teams ship real AI features — through rapid audits, prototypes, and integration support.',
    tools: 'Claude API · Python · React Native',
    lede: 'The best AI feature is the one that disappears into the product.',
    body: 'I work with app teams — usually through Ion Studio — to identify where AI creates genuine value (not novelty), prototype rapidly, and hand off specs the team can actually ship. I\'m especially interested in AI that works quietly: features users rely on without thinking of them as "AI."',
    methods: [
      { name: 'AI opportunity audits', detail: 'Structured review of existing apps to find 3–5 AI integration moments.' },
      { name: 'Rapid prototyping', detail: 'Working AI prototypes in weeks, not quarters.' },
      { name: 'Integration handoff', detail: 'Specs and support through the first AI feature ship.' },
      { name: 'Responsible integration', detail: 'Building in transparency, fallbacks, and honest capability boundaries.' },
    ],
    relatedProjectIds: [1, 2],
  },
  {
    slug: 'data-analytics',
    tone: 'lilac', tag: 'FOCUS 03',
    title: 'Data & Analytics',
    short: 'Analysis, dashboards, and statistical tools that help teams make better decisions — not just prettier charts.',
    tools: 'Python · SQL · Tableau',
    lede: 'A chart is a paragraph. If it doesn\'t earn its place, cut it.',
    body: 'I build data tools and analysis that serve an actual decision, not a metric inventory. My approach is audience-first: what the CEO needs to see is different from what the product team needs to act on. I\'m especially careful about what the data can and can\'t honestly say.',
    methods: [
      { name: 'Statistical analysis', detail: 'A/B testing, significance testing, regression — with honest interpretation.' },
      { name: 'Decision dashboards', detail: 'Dashboards built around a specific decision, not a data dump.' },
      { name: 'Data tooling', detail: 'Custom calculators and tools when nothing off-the-shelf is honest enough.' },
      { name: 'Audience-first framing', detail: 'Different outputs for the board, the team, and the curious generalist.' },
    ],
    relatedProjectIds: [6],
  },
  {
    slug: 'web-development',
    tone: 'moss', tag: 'FOCUS 04',
    title: 'Web Development',
    short: 'Building web experiences — from interactive campus guides to SharePoint infrastructure at ANU.',
    tools: 'React · JavaScript · SharePoint',
    lede: 'The web should work for everyone on the first visit.',
    body: 'I build web products and internal platforms — from public-facing interactive experiences to organisational SharePoint infrastructure. My work at ANU as Web Project Officer covered both ends: public student-facing products and the internal systems that keep things running.',
    methods: [
      { name: 'Interactive experiences', detail: 'Web-based guides, explorers, and tools for public audiences.' },
      { name: 'SharePoint development', detail: 'Internal platforms, intranet design, and process automation.' },
      { name: 'React development', detail: 'Component-based UIs — including this portfolio.' },
      { name: 'Performance & accessibility', detail: 'Fast, accessible experiences that work on the first visit, not just in Figma.' },
    ],
    relatedProjectIds: [5, 3],
  },
];

window.UPCOMING = [
  {
    id: 'u1', slug: 'villain-predictor',
    title: 'Villain <em>Predictor</em>',
    cat: 'Data · NLP',
    teaser: 'Document analysis tool that identifies villain archetypes in narrative text — entity recognition, sentiment patterns, and story structure analysis.',
    tone: 'ink', status: 'planned', category: 'data', glyph: 'star',
    lede: 'Can an NLP model identify a villain before the plot formally introduces one? That\'s the question driving this.',
    role: 'Solo project', year: 2026,
    sections: [
      { kind: 'block', tag: 'Concept', title: 'Villainy as a data problem.', body: 'Every compelling villain follows structural patterns — a power imbalance, a moment of choice, an escalating arc. This project treats those patterns as extractable features. The goal is a document analysis tool that identifies villain archetypes using named entity recognition, sentiment trajectory analysis, and narrative arc markers. Not labelling characters good or evil, but surfacing the signals authors use to prime readers.' },
      { kind: 'block', tag: 'Approach', title: 'What the text signals before the reader knows.', body: 'Authors signal villainy well before the reveal — through linguistic framing, sentiment shifts around a character, and the sequence of actions they\'re associated with. Early experiments on classic texts show consistent structural patterns: sentiment collapse around a named entity typically precedes the plot\'s formal villain declaration by several chapters. The tool is designed to surface these patterns, not make moral judgements.' },
      { kind: 'metrics', items: [
        { num: 'NLP', label: 'Core technique' },
        { num: '3', label: 'Archetype patterns identified in early testing' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected first version' },
      ] },
      { kind: 'block', tag: 'Why', title: 'Part analytical tool, part creative toy.', body: 'The practical use case is literary content analysis — useful for editors, researchers, and narrative teams who want structured insight into how their stories signal character intent. But honestly, this started because I wanted to know whether a model could identify Iago as trouble from Act I\'s language alone, before any action confirmed it. That question is still the one driving the work.' },
    ],
  },
  {
    id: 'u2', slug: 'anu-course-recommender',
    title: 'ANU Course <em>Recommender</em>',
    cat: 'Data · EdTech',
    teaser: 'A personalised course recommendation system for ANU students — using academic history, career goals, and enrolment patterns to surface the right next step.',
    tone: 'moss', status: 'planned', category: 'data', glyph: 'globe',
    lede: 'Most students pick courses based on what their friends are taking, or what fits a timetable gap. This tool is an attempt to do better.',
    role: 'Solo project', year: 2026,
    sections: [
      { kind: 'block', tag: 'Concept', title: 'Course selection is a hard problem.', body: 'ANU offers hundreds of courses across dozens of programs. The flexible degree structure means students have genuine choice — but most lack the context to use it well. A recommendation system that knows your academic history, your stated career interests, and what students like you found useful could make that choice feel navigable rather than overwhelming.' },
      { kind: 'metrics', items: [
        { num: 'Data · EdTech', label: 'Category' },
        { num: 'ANU', label: 'Target context' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected' },
      ]},
      { kind: 'block', tag: 'Why', title: 'Closer to an advisor than a filter.', body: 'The goal isn\'t another search interface. It\'s something that reasons about trajectory — what you\'ve done, where you\'re trying to go, and what the data says helps bridge that gap. The design challenge is making a recommendation feel like genuine advice rather than an algorithm output.' },
    ],
  },
  {
    id: 'u3', slug: 'coffee-stamp-tracker',
    title: 'Coffee Stamp <em>Tracker</em>',
    cat: 'UI/UX · Mobile',
    teaser: 'A digital loyalty stamp app for independent coffee shops — lightweight, no vendor lock-in, works without installing anything on the customer\'s phone.',
    tone: 'cherry', status: 'planned', category: 'ux', glyph: 'heart',
    lede: 'Independent cafes lose regulars to chains partly because chains have apps. This is the lightweight, no-install alternative.',
    role: 'Solo project', year: 2026,
    sections: [
      { kind: 'block', tag: 'Concept', title: 'The stamp card, rebuilt without the paper.', body: 'Most digital loyalty platforms are expensive, require the customer to install an app, and lock the cafe into a contract. This is a QR-based alternative: the customer scans, gets their stamp, no install required. The cafe sets it up in ten minutes and owns their data. No subscriptions, no lock-in.' },
      { kind: 'metrics', items: [
        { num: 'UI/UX · Mobile', label: 'Category' },
        { num: 'No install', label: 'Key constraint' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected' },
      ]},
      { kind: 'block', tag: 'Why', title: 'Built for the cafe I go to every day.', body: 'Recess Cafe doesn\'t have a loyalty system. Most of the independent places I like don\'t. This started as a "what would I actually want as a cafe owner" exercise — something effortless on both sides of the counter, that makes regulars feel noticed without requiring anyone to do much.' },
    ],
  },
  {
    id: 'u4', slug: 'financial-time-machine',
    title: 'Financial Time <em>Machine</em>',
    cat: 'Data · Personal Finance',
    teaser: 'Visualise how financial decisions made in the past would play out with today\'s information — and what that tells you about the choices you\'re making now.',
    tone: 'lilac', status: 'planned', category: 'data', glyph: 'star',
    lede: 'What would you have done differently if you\'d had this information sooner? That question drives the whole thing.',
    role: 'Solo project', year: 2026,
    sections: [
      { kind: 'block', tag: 'Concept', title: 'Hindsight, made useful.', body: 'Most financial tools show you where you are. This one shows you where you could have been — and more usefully, what the current version of that gap looks like for decisions you\'re making today. Input a past financial decision, a time horizon, and a few assumptions. See what the alternate path looked like, and what a comparable choice now might mean.' },
      { kind: 'metrics', items: [
        { num: 'Data · Finance', label: 'Category' },
        { num: 'Client-side', label: 'Architecture' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected' },
      ]},
      { kind: 'block', tag: 'Why', title: 'Decision-making, not data-dumping.', body: 'The goal isn\'t to make you feel bad about the past. It\'s to build intuition about compounding effects and decision timing — the things that are hardest to reason about without a concrete visualisation. The tool is designed to prompt reflection, not optimise regret.' },
    ],
  },
  {
    id: 'u5', slug: 'music-chatbot',
    title: 'Music Recommendation <em>Chatbot</em>',
    cat: 'AI · Music',
    teaser: 'A conversational music recommender that asks what you\'re in the mood for, not what you\'ve listened to — built on Claude API with real music data.',
    tone: 'bubble', status: 'planned', category: 'data', glyph: 'flower',
    lede: 'Spotify knows what you\'ve played. This tries to understand what you actually want right now.',
    role: 'Solo project', year: 2026,
    sections: [
      { kind: 'block', tag: 'Concept', title: 'Mood-first, not history-first.', body: 'Most recommenders optimise for what you\'ve already listened to. That\'s useful for discovering more of the same, but misses the moment when you want something genuinely different. This chatbot starts with a conversation: what are you doing, how are you feeling, what does the next hour need to feel like? Then it recommends. The Claude API handles the natural language; real music data handles the output.' },
      { kind: 'metrics', items: [
        { num: 'Claude API', label: 'Core technology' },
        { num: 'Conversational', label: 'Interaction model' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected' },
      ]},
      { kind: 'block', tag: 'Why', title: 'Because "I\'m feeling nostalgic on a rainy Sunday" is a valid query.', body: 'The thesis is that mood and context are better inputs for music discovery than play history. The engineering challenge is translating a fuzzy emotional description into music metadata — tempo, energy, key, era — without losing the nuance. The design challenge is making a chatbot feel natural, not like a search interface with extra steps.' },
    ],
  },
  {
    id: 'u6', slug: 'sentiment-analysis-tool',
    title: 'Sentiment Analysis <em>Tool</em>',
    cat: 'Data · NLP',
    teaser: 'A clean interface for sentiment analysis — designed for non-technical stakeholders who need to understand what their customers feel, not just a score.',
    tone: 'cherry', status: 'planned', category: 'data', glyph: 'heart',
    lede: 'A sentiment score is a number. This tool is an attempt to make it a conversation.',
    role: 'Solo project', year: 2026,
    sections: [
      { kind: 'block', tag: 'Concept', title: 'Beyond the score.', body: 'Most sentiment analysis tools return a number between -1 and 1. That\'s technically correct and practically useless for anyone who isn\'t already comfortable interpreting it. This tool surfaces sentiment with plain-language summaries, trend visualisations, and example extracts — designed for the marketing lead or product manager who needs to act on the finding, not analyse the model.' },
      { kind: 'metrics', items: [
        { num: 'NLP', label: 'Core technique' },
        { num: 'Non-technical', label: 'Target audience' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected' },
      ]},
      { kind: 'block', tag: 'Why', title: 'The communication gap in data tools.', body: 'I\'ve sat in enough stakeholder meetings where a data output needed a ten-minute explanation before it was useful. The analysis isn\'t the hard part — making it legible to the person who needs to act on it is. This tool is a response to that gap: NLP results presented as insight, not as data.' },
    ],
  },
  {
    id: 'u7', slug: 'revamp-stories',
    title: '<em>Stories</em> Revamp',
    cat: 'UI/UX · Web',
    teaser: 'A redesign of the ANU Stories content platform — better editorial layout, improved discoverability, and a CMS experience that doesn\'t require a manual.',
    tone: 'ink', status: 'planned', category: 'ux', glyph: 'pin',
    lede: 'ANU Stories has great content and a layout that works against it. This is the redesign case study.',
    role: 'Web Project Officer, ANU', year: 2026,
    sections: [
      { kind: 'block', tag: 'Context', title: 'A content platform that buries its content.', body: 'ANU Stories publishes research, features, and institutional content — some of it genuinely compelling. The problem is discoverability: stories are hard to browse, the editorial hierarchy doesn\'t reflect content quality, and the CMS workflow adds friction for contributors. A redesign focused on surfacing good content more efficiently and making the publishing experience less painful.' },
      { kind: 'metrics', items: [
        { num: 'UI/UX · Web', label: 'Category' },
        { num: 'ANU', label: 'Client' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected' },
      ]},
      { kind: 'block', tag: 'Approach', title: 'Editorial design as navigation design.', body: 'The approach treats layout decisions as navigation decisions — how a story is presented determines whether a reader continues. The redesign tests a card-based browsing model, a simplified tagging taxonomy, and a CMS interface that surfaces the most common publishing tasks without requiring documentation. Still in early research phase.' },
    ],
  },
  {
    id: 'u8', slug: 'real-estate-prediction',
    title: 'Real Estate Price <em>Prediction</em>',
    cat: 'Data · Machine Learning',
    teaser: 'ML model for Canberra property prices — with a dashboard that explains the prediction and what drove it, not just the number.',
    tone: 'moss', status: 'planned', category: 'data', glyph: 'pin',
    lede: 'Property price prediction is a solved problem in the literature. Building a dashboard that makes the prediction honest and explainable is the interesting part.',
    role: 'Solo project', year: 2026,
    sections: [
      { kind: 'block', tag: 'Concept', title: 'Prediction plus explanation.', body: 'Most property price tools give you a number. This one gives you a number and shows you what drove it — the three or four features that had the most weight in this specific prediction, and what it would take to move the price estimate meaningfully. The goal is a tool that builds understanding, not just outputs an estimate.' },
      { kind: 'metrics', items: [
        { num: 'ML · Data', label: 'Category' },
        { num: 'Canberra', label: 'Market focus' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected' },
      ]},
      { kind: 'block', tag: 'Why', title: 'Explainability as a design requirement.', body: 'A model that predicts well but can\'t explain itself isn\'t useful to most people. This project treats explainability as a first-class design requirement alongside accuracy — the feature importance output and the uncertainty range are as much a part of the user experience as the prediction itself.' },
    ],
  },
  {
    id: 'u9', slug: 'customer-churn',
    title: 'Customer Churn <em>Model</em>',
    cat: 'Data · Machine Learning',
    teaser: 'Predicting customer churn before it happens — and designing the intervention alongside the model, not as an afterthought.',
    tone: 'lilac', status: 'planned', category: 'data', glyph: 'globe',
    lede: 'The model is the easy part. Knowing what to do with the prediction is what this project is actually about.',
    role: 'Solo project', year: 2026,
    sections: [
      { kind: 'block', tag: 'Concept', title: 'Churn prediction and churn response.', body: 'Most churn models stop at the prediction: this customer is likely to leave in the next 30 days. What that means for the team trying to act on it depends entirely on the business context — what levers are available, what the cost of intervention is, and what "saving" a customer actually looks like. This project builds the model and the intervention framework together.' },
      { kind: 'metrics', items: [
        { num: 'ML · Data', label: 'Category' },
        { num: 'Intervention design', label: 'Key focus' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected' },
      ]},
      { kind: 'block', tag: 'Why', title: 'A model without a use case is a demo.', body: 'I\'ve seen too many ML projects ship a model and call it done, leaving the team that needs to act on it to figure out the rest. This project is an attempt to build the whole thing — prediction, interpretation, and recommended response — as an integrated product.' },
    ],
  },
  {
    id: 'u10', slug: 'personalised-resume-generator',
    title: 'Resume <em>Generator</em>',
    cat: 'AI · Productivity',
    teaser: 'AI-powered resume tailoring to a specific job description — with transparent output about what changed and why, so you stay in control.',
    tone: 'cherry', status: 'planned', category: 'data', glyph: 'flame',
    lede: 'AI resume tools exist. Most of them optimise for keywords and produce something that sounds like nobody wrote it.',
    role: 'Solo project', year: 2026,
    sections: [
      { kind: 'block', tag: 'Concept', title: 'Tailored, not rewritten.', body: 'The difference between a generic resume and a good application is specificity — connecting your actual experience to what this particular role needs. This tool takes your base resume and a job description and surfaces the best match: what to emphasise, what to reframe, what to cut. Crucially, it shows its reasoning — you\'re editing with understanding, not accepting output blindly.' },
      { kind: 'metrics', items: [
        { num: 'Claude API', label: 'Core technology' },
        { num: 'Transparent', label: 'Output design' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected' },
      ]},
      { kind: 'block', tag: 'Why', title: 'Staying in control of your own story.', body: 'The design constraint is transparency: every suggestion the tool makes should come with a reason, and the user should feel like they\'re making a more informed edit, not outsourcing their voice to a model. Especially important for a document that represents you to a hiring panel.' },
    ],
  },
  {
    id: 'u11', slug: 'sound-emotion-visualiser',
    title: 'Sound to Emotion <em>Visualiser</em>',
    cat: 'Creative · Data',
    teaser: 'Real-time audio analysis mapped to emotion and rendered as live visuals — a creative tool at the intersection of music, data, and feeling.',
    tone: 'bubble', status: 'planned', category: 'data', glyph: 'flower',
    lede: 'What does music look like when you try to draw what it feels like rather than what it sounds like?',
    role: 'Solo project', year: 2026,
    sections: [
      { kind: 'block', tag: 'Concept', title: 'Emotion as a rendering target.', body: 'Real-time audio analysis — tempo, key, energy, timbre — mapped to a visual language built around emotional categories rather than acoustic properties. The output isn\'t a waveform or an equaliser; it\'s something closer to how music actually feels. Part creative tool, part data visualisation experiment.' },
      { kind: 'metrics', items: [
        { num: 'Creative · Data', label: 'Category' },
        { num: 'Real-time', label: 'Rendering' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected' },
      ]},
      { kind: 'block', tag: 'Why', title: 'The space between data and feeling.', body: 'Most data visualisation tries to be precise. This one tries to be evocative. The challenge is building a visual vocabulary for emotional content without it becoming arbitrary — grounding the aesthetic choices in the actual audio features, so the result feels like a consequence of the music rather than a decoration.' },
    ],
  },
  {
    id: 'u12', slug: 'stock-price-dashboard',
    title: 'Stock Price <em>Dashboard</em>',
    cat: 'Data · Finance',
    teaser: 'A stock prediction dashboard that surfaces uncertainty as prominently as the forecast — because the confidence interval is the most useful part.',
    tone: 'moss', status: 'planned', category: 'data', glyph: 'star',
    lede: 'Most prediction dashboards hide the uncertainty. This one treats it as the main event.',
    role: 'Solo project', year: 2026,
    sections: [
      { kind: 'block', tag: 'Concept', title: 'Honest forecasting.', body: 'Stock price prediction models are plentiful. What most dashboards don\'t show is what the model actually knows versus what it\'s guessing — the prediction interval, the model\'s historical accuracy on similar conditions, and the scenarios that would invalidate the forecast. This dashboard makes that uncertainty visible and central, not buried in a footnote.' },
      { kind: 'metrics', items: [
        { num: 'Data · Finance', label: 'Category' },
        { num: 'Uncertainty-first', label: 'Design approach' },
        { num: 'Concept', label: 'Current stage' },
        { num: '~2026', label: 'Expected' },
      ]},
      { kind: 'block', tag: 'Why', title: 'Confidence intervals are the product.', body: 'A point estimate without a confidence range is a guess dressed as a fact. The design principle here is that the uncertainty quantification is as important as the forecast — and should be presented that way, not as a caveat but as the core output. The target user is someone making a real decision who needs to know what they don\'t know.' },
    ],
  },
];

window.LEARNING = [
  {
    id: 1, slug: 'google-ux',
    title: 'Google UX Design Certificate',
    provider: 'Google', platform: 'Coursera',
    status: 'planned',
    desc: 'A seven-course professional certificate covering UX research, wireframing, prototyping, and usability testing.',
    lede: 'A structured introduction to UX practice from Google — covering the full design process from empathy mapping through high-fidelity prototypes.',
    tone: 'cherry', glyph: 'compass',
    sections: [
      { kind: 'block', tag: 'Why this cert', title: 'Foundation over credential.', body: 'Most of what I know about UX came from doing — designing real products for real users. This certificate is about formalising that knowledge: filling in the gaps, learning the vocabulary, and being rigorous about the parts I\'ve been intuiting. Google\'s curriculum is industry-respected and well-structured, which makes it a useful benchmark.' },
      { kind: 'metrics', items: [
        { num: '7', label: 'Courses in the certificate' },
        { num: 'Coursera', label: 'Platform' },
        { num: 'Planned', label: 'Status' },
        { num: '~6 mo', label: 'Estimated completion' },
      ]},
    ],
  },
  {
    id: 2, slug: 'google-data',
    title: 'Google Data Analytics Certificate',
    provider: 'Google', platform: 'Coursera',
    status: 'planned',
    desc: 'Eight courses covering data analysis using SQL, R, Tableau, and spreadsheets — with a focus on the full analytics workflow.',
    lede: 'Data analytics formalised: from cleaning messy datasets to presenting findings in ways that actually influence decisions.',
    tone: 'moss', glyph: 'star',
    sections: [
      { kind: 'block', tag: 'Why this cert', title: 'Rigour over intuition.', body: 'My data work has always been project-driven — I pick up what I need when I need it. This certificate is an attempt to reverse that: learn the full workflow deliberately, then apply it to real problems. The focus on spreadsheets, SQL, and R together covers the full entry-to-insight pipeline in a way that ad-hoc learning rarely does.' },
      { kind: 'metrics', items: [
        { num: '8', label: 'Courses in the certificate' },
        { num: 'SQL + R', label: 'Core tools' },
        { num: 'Planned', label: 'Status' },
        { num: 'Coursera', label: 'Platform' },
      ]},
    ],
  },
  {
    id: 3, slug: 'microsoft-data',
    title: 'Microsoft Azure Data Fundamentals',
    provider: 'Microsoft', platform: 'Microsoft Learn',
    status: 'planned',
    desc: 'Azure DP-900 certification covering core data concepts, relational and non-relational data, and Azure data services.',
    lede: 'Cloud data fundamentals through the Azure lens — a baseline understanding of how data infrastructure is structured at scale.',
    tone: 'bubblegum', glyph: 'globe',
    sections: [
      { kind: 'block', tag: 'Why this cert', title: 'Architecture shapes query design.', body: 'Snowflake\'s compute-storage separation and multi-cluster virtual warehouse model change how you think about data. Understanding the architecture — how credits are consumed, how caching works, how to avoid full-table scans — changes how you write queries, structure data, and design pipelines. Azure\'s DP-900 covers the conceptual landscape of cloud data without being locked into a single implementation.' },
      { kind: 'metrics', items: [
        { num: 'DP-900', label: 'Exam code' },
        { num: 'Microsoft Learn', label: 'Platform' },
        { num: 'Planned', label: 'Status' },
        { num: 'Foundational', label: 'Level' },
      ]},
    ],
  },
  {
    id: 4, slug: 'databricks',
    title: 'Databricks Data Engineer Associate',
    provider: 'Databricks', platform: 'Databricks Academy',
    status: 'planned',
    desc: 'Associate-level certification covering Delta Lake, Apache Spark, and the Databricks Lakehouse architecture.',
    lede: 'Engineering data pipelines at scale — Databricks\' lakehouse architecture and the Delta Lake paradigm for reliable, performant data.',
    tone: 'moss', glyph: 'flame',
    sections: [
      { kind: 'block', tag: 'Why this cert', title: 'Lakehouse over warehouse.', body: 'The lakehouse architecture is increasingly the default for serious data work — it combines the flexibility of a data lake with the reliability guarantees of a warehouse. Databricks\' associate certification focuses on Delta Lake, which handles versioning, ACID transactions, and schema enforcement in a way that makes large-scale pipelines tractable. Getting rigorous about this layer matters.' },
      { kind: 'metrics', items: [
        { num: 'Spark', label: 'Core engine' },
        { num: 'Delta Lake', label: 'Key technology' },
        { num: 'Planned', label: 'Status' },
        { num: 'Associate', label: 'Level' },
      ]},
    ],
  },
  {
    id: 5, slug: 'snowflake',
    title: 'Snowflake SnowPro Core',
    provider: 'Snowflake', platform: 'Snowflake University',
    status: 'planned',
    desc: 'Core certification covering Snowflake architecture, virtual warehouses, data sharing, and performance optimisation.',
    lede: 'Snowflake\'s architecture is genuinely different from traditional warehouses — this certification is about understanding why, and using that to write better queries.',
    tone: 'lilac', glyph: 'star',
    sections: [
      { kind: 'block', tag: 'Why this cert', title: 'Architecture shapes everything.', body: 'Snowflake\'s compute-storage separation and multi-cluster virtual warehouse model change how you think about data. Understanding the architecture — how credits are consumed, how caching works, how to avoid full-table scans — changes how you write queries, structure data, and design pipelines. The SnowPro Core covers all of this as a foundation.' },
      { kind: 'metrics', items: [
        { num: 'SnowPro', label: 'Certification family' },
        { num: 'Core', label: 'Level' },
        { num: 'Planned', label: 'Status' },
        { num: 'Snowflake University', label: 'Platform' },
      ]},
    ],
  },
  {
    id: 6, slug: 'anthropic',
    title: 'Building with Claude',
    provider: 'Anthropic', platform: 'Anthropic Academy',
    status: 'active', progress: 42,
    desc: 'Practical training on building production applications with Claude — prompt engineering, tool use, the API, and responsible deployment.',
    lede: 'Using Claude as a building block rather than a product — understanding how the API works, where the limits are, and how to design around them.',
    tone: 'cherry', glyph: 'flame',
    sections: [
      { kind: 'block', tag: 'Why this cert', title: 'First-party knowledge from the source.', body: 'There\'s a lot of content about using LLMs from third-party sources. Getting it from Anthropic directly means understanding the actual constraints, capabilities, and design philosophy behind Claude — not a community\'s interpretation of it. For anyone building AI-assisted products, that distinction matters: you write better prompts and make better architectural decisions when you understand what the model is actually doing.' },
      { kind: 'metrics', items: [
        { num: '42%', label: 'Progress' },
        { num: 'In Progress', label: 'Status' },
        { num: 'Anthropic', label: 'Provider' },
        { num: 'API + Prompting', label: 'Focus' },
      ]},
    ],
  },
  {
    id: 7, slug: 'linkedin-learning',
    title: 'LinkedIn Learning Paths',
    provider: 'LinkedIn', platform: 'LinkedIn Learning',
    status: 'active', progress: 65,
    desc: 'A curated set of learning paths across UX design, data analytics, and project management — ongoing professional development.',
    lede: 'Continuous learning across the disciplines I work in — not one certificate but an ongoing practice of staying current.',
    tone: 'bubblegum', glyph: 'book',
    sections: [
      { kind: 'block', tag: 'Why this cert', title: 'Breadth as strategy.', body: 'Not every skill needs deep certification — sometimes you need to understand enough to collaborate effectively, evaluate work, or ask the right questions. LinkedIn Learning\'s shorter format is ideal for breadth: understanding project management methodology, accessibility standards, or data visualisation principles at a level that informs practice without requiring full certification depth.' },
      { kind: 'metrics', items: [
        { num: '65%', label: 'Progress on current path' },
        { num: 'In Progress', label: 'Status' },
        { num: 'LinkedIn', label: 'Provider' },
        { num: 'Ongoing', label: 'Format' },
      ]},
    ],
  },
  {
    id: 8, slug: 'docker',
    title: 'Docker Foundations',
    provider: 'Docker', platform: 'Docker Learning',
    status: 'planned',
    desc: 'Containerisation fundamentals — images, containers, Docker Compose, and deployment basics for modern software delivery.',
    lede: 'Containers are the default unit of deployment now. Understanding Docker properly means writing code that actually works the same way everywhere.',
    tone: 'ink', glyph: 'compass',
    sections: [
      { kind: 'block', tag: 'Why this cert', title: '"Works on my machine" is not a solution.', body: 'Containerisation solves the environment problem. Understanding Docker properly — not just how to run a container but how images are structured, how networking and volumes work, how Compose orchestrates multi-service applications — changes how you build and ship software. It\'s also increasingly a baseline expectation in any engineering environment, and foundational to understanding cloud-native deployments.' },
      { kind: 'metrics', items: [
        { num: 'Docker', label: 'Provider' },
        { num: 'Foundational', label: 'Level' },
        { num: 'Planned', label: 'Status' },
        { num: 'Containerisation', label: 'Focus' },
      ]},
    ],
  },
];

window.CREATIVE = [
  {
    id: 'c1', slug: 'incognito-2025',
    title: 'Incognito 2025',
    meta: 'Annual Exhibition · 2025',
    tone: 'cherry',
    lede: 'A piece submitted to Incognito — the National Gallery of Australia\'s annual anonymous art sale, where no names or prices are attached until after the purchase.',
    desc: 'Annual anonymous art exhibition and sale at the National Gallery of Australia.',
    sections: [
      { kind: 'block', tag: 'About this work', title: 'Anonymous by design.', body: 'Incognito is the National Gallery of Australia\'s annual fundraiser where artists submit small original works — all the same size, all anonymous, all the same price. Buyers choose based on the work alone, with no knowledge of who made it. It\'s a genuinely unusual format: no hierarchy, no reputation, just the piece itself. Submitting felt like an honest test of whether the work could stand without a name attached.' },
      { kind: 'block', tag: 'The work', title: 'Submitted 2025.', body: 'The piece submitted for 2025 is a small mixed-media work. The anonymity of the exhibition is intentional — details live with the piece, not the documentation.' },
    ],
  },
  {
    id: 'c2', slug: 'incognito-2026',
    title: 'Incognito 2026',
    meta: 'Annual Exhibition · 2026',
    tone: 'bubblegum',
    lede: 'Preparing a piece for the National Gallery of Australia\'s 2026 Incognito exhibition — the annual anonymous art sale.',
    desc: 'Annual anonymous art exhibition and sale at the National Gallery of Australia — 2026 submission in progress.',
    sections: [
      { kind: 'block', tag: 'About this work', title: 'Second year.', body: 'After submitting to Incognito in 2025, the plan is to return for 2026. The anonymous format is something I find genuinely interesting — it flattens the usual art-world signals and forces work to speak on its own terms. The 2026 piece is still in progress; the exhibition\'s constraint (a fixed small format, no identifying information) is the starting condition.' },
      { kind: 'block', tag: 'Status', title: 'In progress.', body: 'The 2026 submission is being developed. This page will be updated as the work takes shape.' },
    ],
  },
  {
    id: 'c3', slug: 'other-artworks',
    title: 'Other Artworks',
    meta: 'Ongoing · Mixed Media',
    tone: 'lilac',
    lede: 'A collection of smaller works, experiments, and creative practice made outside of formal exhibitions.',
    desc: 'Ongoing creative practice — illustrations, mixed media, and experiments that don\'t fit a single category.',
    sections: [
      { kind: 'block', tag: 'About', title: 'Practice as process.', body: 'Not everything made needs to be exhibited. A lot of creative work is practice — experimenting with materials, learning by making, building the muscle memory that makes the exhibited pieces better. This page collects the work that doesn\'t fit neatly into a named project: illustrations, colour studies, mixed media experiments, and things that exist somewhere between finished and abandoned.' },
      { kind: 'block', tag: 'Format', title: 'Mixed and ongoing.', body: 'The medium varies — pencil, ink, digital, collage. The common thread is that these are made for the making, not for an audience. More detail and images to follow.' },
    ],
  },
];

